### ISSUE TITLE
Inverse transform

### ISSUE THREAD

**Issue by KafeelBasha** [rnorm/CatEncoders#2]
Hello

When I am trying to get predicted labels by doing inverse transformation using inverse.transform() function in "CatEncoders" package it returns NA as one of the label, below is the screenshot.
![ec](https://user-images.githubusercontent.com/22866208/50723072-c0915b80-10fe-11e9-8b8d-313537af5021.PNG)

For encoding labels I have used below code
```
library(CatEncoders)
ec=LabelEncoder.fit(y_train)


y_lab_train=transform(ec,y_train)
y_lab_test=transform(ec,y_test)
```
Let me know if I am going wrong anywhere.

**Comment by rnorm** [comment]
@KafeelBasha could you provide a reproducible example so that I can help?
Thanks!

**Comment by KafeelBasha** [comment]
Hello

Below is the example. Let me know where I am going wrong. 

As per the encoding, we don't have value 0,but while predicting R returns a label 0. Help me with the reason for getting 0 while predicting the labels and NA when we do inverse transform.
```
library(keras)
#Stack-overflow data
data=read.csv("https://storage.googleapis.com/tensorflow-workshop-examples/stack-overflow-data.csv",stringsAsFactors = FALSE)

#Train and test split
set.seed(200)
index=sample(nrow(data),nrow(data)*0.8)
train=data[index,]
test=data[-index,]
x_train=train$post
y_train=train$tags
x_test=test$post
y_test=test$tags

#Label Encoder
library(CatEncoders)
ec=LabelEncoder.fit(y_train)
ec@classes
train_labels=transform(ec,y_train)
#For Test set
test_labels=transform(ec,y_test)

mw=10000 #Maximum # words
seq_len=100
#Tokenizer
tokenizer=text_tokenizer(num_words = mw)
#Split text into words and assign an integer id
token_fit=fit_text_tokenizer(tokenizer,x_train)
# Create a sequence
sequence=texts_to_sequences(token_fit,x_train)
#Padding the sequence
train_features=pad_sequences(sequence,maxlen=seq_len)
dim(train_features)

#Create test features
#Create a sequence for test set
seq_test=texts_to_sequences(token_fit,x_test)

#Padding the test sequence
test_features=pad_sequences(seq_test,maxlen=seq_len)
dim(test_features)

#One hot encoding
y_labels_train=to_categorical(train_labels)[,-1]
#dim(y_labels_train)
y_labels_test=to_categorical(test_labels)[,-1]

#Model
model=keras_model_sequential()
model%>%layer_embedding(input_dim=mw,output_dim = 64,input_length = seq_len)%>%layer_flatten()%>%layer_dense(1024,activation="relu")%>%layer_dense(20,activation="softmax")
summary(model)
#Compile and fit the model
model%>%compile(optimizer="rmsprop",loss="categorical_crossentropy",metrics="accuracy")
model%>%fit(train_features,y_labels_train,epochs=3,batch_size = 32,validation_split = 0.2)

pred=predict_classes(model,test_features) #Prediction has 0 labels
class(pred)
pred_labels=inverse.transform(ec,as.integer(pred)) #Requires a vector
class(pred_labels)
head(pred_labels,25)
```

Thanks

**Comment by KafeelBasha** [comment]
Hello
I was doing some research on why I am getting label 0 in predicted classes using predict_classes(). 
The reason is Keras expects an integer vector from 0 to num_classes, then I have to change my one hot encoding part as below.
```
y_labels_train=to_categorical(train_labels-1)
y_labels_test=to_categorical(test_labels-1)
```
After changing the one hot encoding part, I re run the model but still I am getting NA in inverse transform.

**Comment by KafeelBasha** [comment]
Instead of using the package "CatEncoders" to encode labels, I have defined below function

#Label Encoder
enc<-function(x){
  as.numeric(factor(x))-1
}
Then matching the class labels using below table.
imageimage.png792×154 3.23 KB
Now I am getting desired result.
Thanks
